### ISSUE TITLE
Enabling custom commit message templates

### ISSUE THREAD

**Issue by harrysolovay** [changesets/action#10]
This action can't be used in conjunction with varying commit linting configurations, as there's no way to customize the template from which the commit message is generated. I'm trying to use `commitlint` with a conventional commits config. I see that the action is writing the following commit messages...

**when commiting for the sake of PR generation**: `CHANGESET: thick-mayflies-learn...`
**when commiting version bumps**: `Version Packages`

This causes any commit-linting CI to fail with something along the following lines:

<img width="335" alt="Screen Shot 2019-12-19 at 8 31 18 AM" src="https://user-images.githubusercontent.com/4893548/71190931-4936d800-223a-11ea-8395-6aa8468a3e98.png">

Side node: the placeholders (`thick-mayflies-learn...`) are awesome. Very tasteful.

**Comment by Noviny** [comment]
Is this using the action to create the PRs?

For most use-cases, I recommend having the `commit` flag in config set to false, but if our CLI is breaking this, I agree this needs to be configurable.

(one of our goals is to have no ownership of how you git, so you can git however you think is best)

I'm probably not going to have immediate time to jump on this btw, but will add some labels.

**Comment by jorenbroekema** [comment]
This can be closed I think, it works now:

Example:

```yaml
- name: Create Release Pull Request or Publish to npm
  id: changesets
  uses: changesets/action@master
  with:
    # This expects you to have a script called release which does a build for your packages and calls changeset publish
    publish: npm run release
    commit: "chore: release"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```
