### ISSUE TITLE
Feature Request: Expose hasChangesets

### ISSUE THREAD

**Issue by wweaver** [changesets/action#135]
I'm looking for a way to create tags at the time of publish instead of actually publishing. I'm working with a monorepo but we don't publish to npm. We instead are trying to use this as a deploy job. The creation of a version PR works nicely but I'm trying to find a simple way to hook into when the version PR is merged to generate the corresponding tags but not perform the publish. I thought the simplest way to do this would be to provide the additional output from this script so I can add this new flow.

```yaml
            - name: Create Release Pull Request
              uses: changesets/action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create Tags
              if: "!steps.changesets.output.hasChangesets"
              run: pnpm changeset tag && git push --tags
```

If there's a better way I'm all for any input!

I had tried to do this as I thought this was overriding the publish command and I'd have to call `changeset publish` manually, but it seems like it's a separate script and the `changeset publish` is called automatically anyway.

```yaml
            - name: Create Release Pull Request
              uses: changesets/action@v1
              with:
                  publish: pnpm publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
