### ISSUE TITLE
pnpm cache directory added to version control during release workflow

### ISSUE THREAD

**Issue by robphoenix** [changesets/action#146]
During my Github Actions release workflow the pnpm cache directory (`.pnpm-store/`) is being included in version control, resulting in a massive PR. This is happening during the `changeset version` command.

![image](https://user-images.githubusercontent.com/9257284/152176536-fc6ea9fd-3a31-4d95-96f4-6a7bd316288c.png)

![image](https://user-images.githubusercontent.com/9257284/152176659-1de54633-d431-4d7b-9e76-1561a077e37a.png)

<details>
<summary>Workflow file</summary>

```yaml
name: Release
on:
  push:
    branches:
      - main
env:
  CI: true
  PNPM_CACHE_FOLDER: ${{ github.workspace }}/.pnpm-store

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can
          # generate changelogs with the correct commits
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: Setup pnpm config
        run: pnpm config set store-dir ${{ env.PNPM_CACHE_FOLDER }}
      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: "chore: version packages"
          title: "Version Packages"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

</details>

<details>
<summary>package.json scripts</summary>

```json
"ci:version": "changeset version && pnpm install --lockfile-only",
"ci:publish": "pnpm build && changeset publish"
```

</details>

I tried adding the cache directory to the root `.gitignore` file but that broke the build

```
Error: Cache folder path is retrieved for pnpm but doesn't exist on disk: /home/runner/work/customer-ui/customer-ui/.pnpm-store/v3
```
