### ISSUE TITLE
Changesets step does not appear in GitHub Actions log

### ISSUE THREAD

**Issue by aomarks** [changesets/action#149]
When we run `changesets/action`, the GitHub actions log *does not show an entry for the changesets release step itself*. This is true both when it succeeds and when it fails. For some reason, the step configured with `with: changesets/action@mater` never shows up there.

This makes it difficult to understand why the release action failed, because all steps appear to have passed. Only by going to "View raw logs" can we see that an error occured inside the `changesets/action` step.

### Actual result

<img src="https://user-images.githubusercontent.com/48894/152852839-f106ab32-0791-4863-af87-6720354a6cc0.png" width="500">

Failing example: https://github.com/lit/lit/runs/5097382794?check_suite_focus=true
Succeeding example: https://github.com/lit/lit/runs/5098179536?check_suite_focus=true

### Expected result

I would expect to see a step called "Create Release Pull Request or Publish to npm" in our action run status.

### Workflow

https://github.com/lit/lit/blob/05b5eb227701cf5886e1c193ac6243f8ea991cb8/.github/workflows/release.yaml#L36
```yaml
- name: Create Release Pull Request or Publish to npm
  id: changesets
  uses: changesets/action@master
  with:
    version: npm run version
    publish: npm run release
  env:
    HUSKY: 0
    GITHUB_TOKEN: ${{ secrets.LIT_ROBOT_AUTOMATION_PAT }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
