### ISSUE TITLE
`yarn install` failing within changesets/action

### ISSUE THREAD

**Issue by egnwd** [changesets/action#170]
## Summary
When running `yarn install` after `changeset version` using yarn 3 the process fails from within changesets/action in a Github Action, but not locally.

## Error
The error I receive is:
`The process '/usr/local/bin/yarn' failed with exit code 1`
along with
`The lockfile would have been modified by this install, which is explicitly forbidden.`

But to me this doesn't make sense as I'm just running `yarn install` and I would expect this to change the lock file as all the versions have been bumped, `--immutable` should explicitly forbid this?

Running `yarn release` locally works as expected and I do not receive this error.

## Context
I have the following workflow:
```yml
name: Changeset

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    name: Create Changeset PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

_Note: the `yarn install --immutable` before the `yarn release` step runs fine and installs everything as expected._

in the root package.json I have:

```json
    "release": "changeset version && yarn diff --yes && yarn prettier --write '{packages,plugins}/*/{package.json,CHANGELOG.md}' && yarn install",
```

The last command is `yarn install` (no `--immutable`) and this seems to be failing.
I also have the following `.yarnrc.yml` file:
```yml
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs
```
`.yarn/releases/yarn-3.1.1.cjs` is checked in and in the repo's main branch.

Cheers
