### ISSUE TITLE
PR created but action not started

### ISSUE THREAD

**Issue by unional** [changesets/action#187]
You can see that the PR is opened correctly: https://github.com/unional/clibuilder/pull/375
But there is no workflow started: https://github.com/unional/clibuilder/actions

I'm setting it up using shared workflow:

```yml
jobs:
  code:
    uses: unional/.github/.github/workflows/yarn2-library-verify-cross-platform.yml@main

  release:
    uses: unional/.github/.github/workflows/yarn2-library-release.yml@main
    needs: code
    secrets: inherit
```
https://github.com/unional/clibuilder/blob/main/.github/workflows/release.yml

```yml
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
https://github.com/unional/.github/blob/main/.github/workflows/yarn2-library-release.yml

Maybe somehow the action is getting wrong information because of that?

**Comment by unional** [comment]
I have another repo with the same problem:
https://github.com/unional/global-store/pull/118

**Comment by abdonrd** [comment]
Same here! https://github.com/Qiskit/web-components/pull/83

**Comment by Saul-Mirone** [comment]
Same here! https://github.com/Saul-Mirone/milkdown/pull/531

**Comment by yishayweb** [comment]
Hey guys
I'm not sure that what I'm experiencing is the same issue, but it seems related
For me, when the 'Version Packages' pr is created, the workflow I have **do run**
But when I merge another changes to master (with a changeset file), and the 'Version Packages' pr is being updated, the workflow doesn't run anymore.
This is the workflow I'm refering to:
[https://github.com/yishayweb/monorepo_pnpm_changesets/blob/master/.github/workflows/verify_changesets.yml](url)
and as you can see, I'm triggering it with
`on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - master`
Hence I expect it to be run each time the 'Version Packages' pr is getting updated
Is it the issue you guys experience?

**Comment by airtonix** [comment]
@yishayweb you can turf all that custom code to test if changesets exist and use either: 
```

jobs:
  Changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
      Changesets: ${{ steps.filter.outputs.Changesets }}
    steps:
      #
      # Not on a Pull Request, so dorny/paths-filter needs a checkout
      #
      - uses: actions/checkout@v2
        with:
          # This may save additional git fetch roundtrip if
          # merge-base is found within latest 20 commits
          fetch-depth: 20
      #
      # Build a list of namespace change flags
      #
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            Changesets:
              - added|modified: '.changesets/!(README)*.md'

            Apps:
              - 'apps/!(*storybook)**/*'

      - run: node -e 'console.log(${{toJson(steps.filter.outputs)}})'

  Changesets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    needs: Changes
    if: needs.Changes.outputs.Changesets
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      # This is to support things like nx.dev affected or changesets
      - name: fetch more git
        run: git fetch --no-tags --prune --depth=5 origin master
        shell: bash
      #
      # Process Changesets
      #
      # If the pushed ref is a branch and that branch name is 'master',
      # and the commit message doesnt look like it was created by processing changesets
      # then lets try processing any changsets.
      - name: Process changesets
        uses: ./.github/actions/process-changesets
```

or you can just use the `changesets/cli` status command with the json output: 

https://github.com/changesets/changesets/tree/main/packages/cli#status

**Comment by kachkaev** [comment]
From [GitHub docs](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs):

> When you use the repository’s GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository’s GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

> Use a repo scoped [Personal Access Token (PAT)](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) created on an account that has write access to the repository that pull requests are being created in. This is the standard workaround and [recommended by GitHub](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token). However, the PAT cannot be scoped to a specific repository so the token becomes a very sensitive secret. If this is a concern, the PAT can instead be created for a dedicated [machine account](https://docs.github.com/en/github/site-policy/github-terms-of-service#3-account-requirements) that has collaborator access to the repository. Also note that because the account that owns the PAT will be the creator of pull requests, that user account will be unable to perform actions such as request changes or approve the pull request.

So the solution could be this:

```diff
       env:
-         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+         GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

`CUSTOM_GITHUB_TOKEN` needs to be generated and added to repo secrets

**Comment by Andarist** [comment]
Yes, @kachkaev's answer is the correct one. Would you be so kind to add a note about this in the README of this action?

**Comment by kachkaev** [comment]
I tried configuring custom git credentials in https://github.com/blockprotocol/blockprotocol/pull/535/files

However, this did not help. Here is what I see [in the ‘Version Packages’ PR](https://github.com/blockprotocol/blockprotocol/pull/529):

<img width="857" alt="Screenshot 2022-08-25 at 13 55 44" src="https://user-images.githubusercontent.com/608862/186670789-3610076b-7520-48be-82ad-d7e6f7f2f008.png">

Commit metadata matches new environment variables that I’ve set:

```
commit 7fda46e1286e2b815b5f94b76e8532ce491edcd5 (HEAD, origin/changeset-release/main)
Author: hashdotai <63675132+hashdotai@users.noreply.github.com>
Date:   Thu Aug 25 12:53:17 2022 +0000

    Version Packages
```

The push though is still done by `github-actions[bot]` so checks are not triggered. 🤔 Because _Linting_ is a required check, the PR cannot be merged unless a developer force-pushes to the branch just before releasing new versions.

**Comment by Andarist** [comment]
This is surprising to me and, unfortunately, I don't know the answer to this problem. Perhaps it would be worth opening a ticket with GitHub support to learn what are the exact requirements for workflows to be executed. However, if I take a look at [this commit](https://github.com/developit/microbundle/commit/c76c41f8317611f7592d8e44c569e8083076f25f) and [the related PR](https://github.com/developit/microbundle/pull/958) then I can see that workflows were correctly executed for both. So perhaps this is an issue in your setup. As far as I can see they only provide a custom token and nothing more:
https://github.com/developit/microbundle/blob/60b5edcf5d96c26877134febbdf0a247ee56b9c7/.github/workflows/release.yml#L34

**Comment by kachkaev** [comment]
Thanks for sharing a link to https://github.com/developit/microbundle/pull/958 @Andarist – interesting! 

If we look at individual commits in this PR, we can see the same pattern as in https://github.com/blockprotocol/blockprotocol/pull/529. The [first commit](https://github.com/developit/microbundle/commit/fd160b2f93b936639a4be3598745b73d6bfc91ea) has ✅, but all the following force-pushed ones lack CI checks ([1](https://github.com/developit/microbundle/commit/428f9493b4cc1dc0fe22e823b694572aafd015fd), [2](https://github.com/developit/microbundle/commit/134ed291a283c4a480568d711184cfdf23222f52), [3](https://github.com/developit/microbundle/commit/164e9057276d2d08840b547c500e093c4ccbe539), ...). All commits are authored by __github-actions[bot]__ despite `GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}` [in release.yml](https://github.com/developit/microbundle/blob/60b5edcf5d96c26877134febbdf0a247ee56b9c7/.github/workflows/release.yml#L34).

The PR is then closed and reopened, which seems to work as a trigger for GitHub Actions. [CI runs](https://github.com/developit/microbundle/actions/runs/2841722819) for the latest __github-actions[bot]__’s commit but is marked as triggered by a human.

<img width="346" alt="Screenshot 2022-08-25 at 18 17 42" src="https://user-images.githubusercontent.com/608862/186728929-cad362f5-c9fd-4398-9b78-8fa1fd05d5e4.png">

<img width="803" alt="Screenshot 2022-08-25 at 18 19 06" src="https://user-images.githubusercontent.com/608862/186729247-8c5b22e8-1493-4031-803b-53953d88cf64.png">

I tried closing and re-opening https://github.com/blockprotocol/blockprotocol/pull/529 and CI got triggered too. That’s a bit hacky but I don’t see any alternatives at this point. Unless I miss something, redefining `GITHUB_TOKEN` only changes the author of the PR and triggers actions for the first commit in it.

**Comment by Andarist** [comment]
This is bizarre... 🙈 it would really be lovely if we could create a GitHub support ticket about this. Would you be willing to do this? You already have all the required context to explain the issue properly

**Comment by kachkaev** [comment]
I think I figured it out. Here is my final solution:

```diff 
 jobs:
   release:
     runs-on: ubuntu-latest
     if: github.repository == 'org/repo'
     steps:
       - uses: actions/checkout@v3
+        with:
+          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

       - uses: ./.github/actions/warm-up-repo
 
       - name: Create Release Pull Request or Publish to npm
         uses: changesets/action@v1.3.0
         with:
           publish: yarn changeset publish
         env:
+          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

[release.yml](https://github.com/blockprotocol/blockprotocol/blob/92765963d8bb9b18ef6c783539ccb1585bf1cb27/.github/workflows/release.yml)

When the action calls `git push`, it uses the same token as the one that was used during checkout. This explains why setting `GITHUB_TOKEN` only in `changesets/action` does not change the account that has force-pushed.

Resulting PR: https://github.com/blockprotocol/blockprotocol/pull/542

<img width="920" alt="Screenshot 2022-08-26 at 13 07 33" src="https://user-images.githubusercontent.com/608862/186900175-4731ed4a-3946-4a48-ae48-bca1fd8035de.png">

CI runs for each new commit:
- ✅ https://github.com/blockprotocol/blockprotocol/commit/5d912deee6c862857ff05fd481e7e5167bf0eda6
- ✅ https://github.com/blockprotocol/blockprotocol/commit/ae9b69fc92c2b1b25b8da037d5d4b73ca1c1566c
- ...

Now that I know that [closing and reopening a PR](https://github.com/changesets/action/issues/187#issuecomment-1227559013) replaces `GITHUB_TOKEN`, I wonder if it’s actually better. 😅 If every new push to ‘Version Packages’ triggers all GitHub workflows, that’s quite a few CI minutes wasted 😬

**Comment by Andarist** [comment]
> If every new push to ‘Version Packages’ triggers all GitHub workflows, that’s quite a few CI minutes wasted 😬

Yeah, in theory, you could craft a more complex pipeline that would wait for the CI checks on your base branch before updating the versioning PR and skip jobs there because they would be somewhat redundant if you have already run jobs on the base branch. It would be great to block the ability to merge the versioning PR when there is a pending CI job on the base branch too.

Would you be willing to add all of this information to the README, with the tradeoffs mentioned there?

**Comment by kachkaev** [comment]
> Would you be willing to add all of this information to the README, with the tradeoffs mentioned there?

I can try next week, but feel free to do this earlier if you want! It will close this issue I guess.

**Comment by kachkaev** [comment]
> Yeah, in theory, you could craft a more complex pipeline that would wait for the CI checks

Possibly, yes. Here is another idea, which may work together with yours. Before `force-pushing`,

1. Create commit to force-push

1. Checkout latest commit from `changeset-release/main `

1. If diffs are equal, don't force push

‘Version Packages’ will be out of date with main, but that's ok – it is always possible to press the Update button. Importantly, CI checks in this PR will only run when some creates a new `changeset/*.md` file rather than on every PR merge to `main`. This would help a lot in our monorepo, because we rarely change packages, but make a lot of tweaks to a web app. Only a fraction of PRs affect the diff in ‘Version Packages’.

**Comment by BPScott** [comment]
Github just shipped https://github.blog/changelog/2022-09-08-github-actions-use-github_token-with-workflow_dispatch-and-repository_dispatch/

Perhaps there could be a mechanism where users specify a set of actions that need to be triggered on the Version Packages PR after it is created/updated. It seems like that'd allow CI runs to occur without needing custom tokens.

Something like:

- user adds `workflow_dispatch` as an allowed trigger on an action (e.g. `my-ci-action.yml`) that runs CI checks
- user adds a `with: {trigger_jobs_on_pr: ['my-ci-action']}` to the with object of the changsets action
- Changesets triggers those jobs on the created PR.

**Comment by Andarist** [comment]
If you could prototype this - it would be kinda cool.

**Comment by shawnthye-guru** [comment]
Another is to allow setting to create Draft PR, so that when a actually person made [Ready for Review], then workflow will run?

**Comment by LukasHechenberger** [comment]
I think @kachkaev 's solution is pretty solid, thanks a lot! Actually, it turns out you only need the "other" token for the checkout: If you use the original in the `changesets/action` step, the PR is created by `github-actions [bot]` and other push actions are triggered as expected:

```diff
  name: Changesets
  
  on:
    push:
      branches:
        - main
  
  concurrency: ${{ github.workflow }}-${{ github.ref }}
  
  jobs:
    release:
      name: Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
          with:
+           # The "other" token
+           token: ${{ secrets.CHANGESETS_GITHUB_TOKEN }}
            # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
            fetch-depth: 0
  
        # Setup node, install, ...
  
        - name: Create Release Pull Request or Publish to npm
          id: changesets
          uses: changesets/action@v1
          env:
            # You can use the original token here!
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

```

**Comment by StyleShit** [comment]
> I think I figured it out. Here is my final solution:
> 
> ```diff
>  jobs:
>    release:
>      runs-on: ubuntu-latest
>      if: github.repository == 'org/repo'
>      steps:
>        - uses: actions/checkout@v3
> +        with:
> +          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
> 
>        - uses: ./.github/actions/warm-up-repo
>  
>        - name: Create Release Pull Request or Publish to npm
>          uses: changesets/action@v1.3.0
>          with:
>            publish: yarn changeset publish
>          env:
> +          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
>            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
> ```
> 
> [release.yml](https://github.com/blockprotocol/blockprotocol/blob/92765963d8bb9b18ef6c783539ccb1585bf1cb27/.github/workflows/release.yml)
> 
> When the action calls `git push`, it uses the same token as the one that was used during checkout. This explains why setting `GITHUB_TOKEN` only in `changesets/action` does not change the account that has force-pushed.
> 
> Resulting PR: [blockprotocol/blockprotocol#542](https://github.com/blockprotocol/blockprotocol/pull/542)
> 
> <img alt="Screenshot 2022-08-26 at 13 07 33" width="920" src="https://user-images.githubusercontent.com/608862/186900175-4731ed4a-3946-4a48-ae48-bca1fd8035de.png">
> 
> CI runs for each new commit:
> 
>     * ✅ [blockprotocol/blockprotocol@5d912de](https://github.com/blockprotocol/blockprotocol/commit/5d912deee6c862857ff05fd481e7e5167bf0eda6)
> 
>     * ✅ [blockprotocol/blockprotocol@ae9b69f](https://github.com/blockprotocol/blockprotocol/commit/ae9b69fc92c2b1b25b8da037d5d4b73ca1c1566c)
> 
>     * ...
> 
> 
> Now that I know that [closing and reopening a PR](https://github.com/changesets/action/issues/187#issuecomment-1227559013) replaces `GITHUB_TOKEN`, I wonder if it’s actually better. 😅 If every new push to ‘Version Packages’ triggers all GitHub workflows, that’s quite a few CI minutes wasted 😬


Thanks! 😄 

This worked for me, but only when passing `setupGitUser: false` to `changesets/action`:

```diff
 - name: Create a Release PR or Publish
   uses: changesets/action@v1
   with:
     publish: npm run release
     commit: 'chore(release): publish'
     title: 'chore(release): publish'
+   setupGitUser: false
   env:
     GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

**Comment by mikeybinns** [comment]
Is there a way to still get PRs / Force-pushes to come from github actions bot when using a custom PAT?
I've tried setting git config directly after checkout with the details taken from [the checkout docs](https://github.com/actions/checkout/tree/v4/?tab=readme-ov-file#push-a-commit-using-the-built-in-token)
![image](https://github.com/user-attachments/assets/282e9877-bd53-40bb-8ae8-651abb1e243a)
And also setting setupGitUser to true directly
![image](https://github.com/user-attachments/assets/ce78d730-c53f-422a-ac12-c420b63ff85d)
![image](https://github.com/user-attachments/assets/a3a0ea74-7971-40e6-a859-1db20f71f8d8)
But the PRs are still created as me instead of the github bot.
I can see it setting
Am I missing something / doing something wrong, or is this just not possible with changesets at the moment?

**Comment by dohooo** [comment]
Nice, @kachkaev's solution works well for me.

**Comment by bd82** [comment]
Personally I like the approach of close/open the PR when intending to merge.
Mainly to avoid unnecessary load on the CI system.
But the problem is that it is a "hack" that is not documented anywhere
So my solution was to "document" it on the PR itself via a comment

```yaml
      - name: Docs on Release Pull Request
        uses: thollander/actions-comment-pull-request@v3
        with:
          # using the `comment-tag` to avoid duplicate comments
          comment-tag: 'pr-release-docs'
          message: |
            To trigger the build for this PR, **close and re-open it**.
            This is necessary because the PR is created by github-actions[bot]
            This is a technical user which does not trigger actions workflows on push events.
            Additionally, this approach reduce load on the CI/CD system (fewer builds).
          pr-number: ${{steps.create_or_update_release_pr.outputs.pullRequestNumber}}

```
