### ISSUE TITLE
Cannot create github release

### ISSUE THREAD

**Issue by iamyoki** [changesets/action#196]
My `release.yml` like this:
```yml
name: Release
on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

## Problem
- Version Packages PR created but without git tag and github realease

## Expected
- Automatically create git tab and github release
