### ISSUE TITLE
Unable to publish with pnpm with github releases

### ISSUE THREAD

**Issue by gamertike** [changesets/action#200]
when i try to use `changeset publish` i get the following error:
https://github.com/guildedts/guilded.ts/runs/7480746311?check_suite_focus=true#step:6:63

but when i use `pnpm -r publish` it works fine. Except for the fact that using this **does not** create a github release for me... Is there anyway can fix this?

**Comment by gamertike** [comment]
**Hey NPM users! I have found a solution!**

Changesets cli has a `tag` command which creates tags for your packages. The reason im tellling you this is because with this command, we can use pnpms `pnpm -r publish` command **with github releases**!

in your package.json, update your publish script to the following:
```json
"scripts": {
    "publish": "changeset tag && pnpm -r publish",
    "version": "changeset version"
}
```

now in your work flow add the following:
```yml
-   name: Create Release Pull Request or Publish to NPM
    uses: changesets/action@v1
    with:
        publish: pnpm run publish
        version: pnpm run version
    env:
        GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.API_NPM_TOKEN }}
```
