### ISSUE TITLE
Add a new input to do GitHub release without npm publishing

### ISSUE THREAD

**Issue by JounQin** [changesets/action#204]
> We're publishing to npm manually at https://github.com/mdx-js/eslint-mdx, and `changeset publish` does not create GitHub releases automatically, this functionality is only available in changesets' action

I recently met this problem again on releasing [`vscode-mdx`](https://github.com/mdx-js/vscode-mdx) which is not a npm package. 😂

See also [#885](https://github.com/changesets/changesets/issues/885)

**Comment by JounQin** [comment]
cc @Andarist

**Comment by khanisak** [comment]
@openscript do you have the answer by now ?

**Comment by schoenwaldnils** [comment]
Had the same problem. I can't remember where I found it. But this was my solution:

```
- name: Create Release Pull Request
  id: changesets
  uses: changesets/action@v1
  with:
    title: 🚀 Release new version
    publish: npx @changesets/cli tag # this will create a new tag and a new release
```
