### ISSUE TITLE
`output.published` is a string, not boolean

### ISSUE THREAD

**Issue by gsuess** [changesets/action#210]
In [the documentation](https://github.com/changesets/action/blob/8c3f5f5637a95a2327e78d5dabcf357978aedcbb/README.md?plain=1#L19) and [here](https://github.com/changesets/action/blob/8c3f5f5637a95a2327e78d5dabcf357978aedcbb/action.yml#L330) it says that the output `published` is boolean type, whereas [here](https://github.com/changesets/action/blob/8c3f5f5637a95a2327e78d5dabcf357978aedcbb/src/index.ts#L45) it looks like that it is a string instead. 

This can cause the a workflow with `if` condition to always fail:
```yaml
  deploy-production:
    uses: ./.github/workflows/deploy.yml

    needs:
      - publish

    if: needs.publish.outputs.published
```

Given that its a string, the last line should be be:

```yaml

    if: needs.publish.outputs.published == 'true'

```
