### ISSUE TITLE
Auto-merge release Pull Request?

### ISSUE THREAD

**Issue by danawoodman** [changesets/action#215]
Is there an option to automatically merge a release PR (eg the "Version Packages" pull request that gets created after pushing changsets)?

I'd like to eliminate one step in pushing releases by just merging these PRs automatically. Is this possible to do with the action directly or is there another way to accomplish this?

**Comment by jsinclair-indeed** [comment]
There's some in-depth discussion already over in #77.

You could always setup your GitHub workflow logic to approve and merge those PRs. You can customise the Changeset PR title to avoid any ambiguous conflicts with any user named PR.s

**Comment by Andarist** [comment]
Ye, while this issue on the surface sounds like a different one - it is essentially the same as #77. Let's keep the discussion there.

**Comment by danawoodman** [comment]
Any guidance on how to auto merge the PR? I've tried like 5 different methods and they all fail in one way or another.

**Comment by danawoodman** [comment]
@jsinclair-indeed do you know how to auto-merge? I'm getting really annoyed with having to keep merging these version release PRs manually since I'm releasing many versions of internal packages daily. I've tried something like this as well as a handful of other approaches:

```yml
name: Auto merge

on:
  pull_request:
    types: [opened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      # Auto merge when the branch name is the changset release branch:
      - name: "Merge pull request"
        if: github.ref_name == 'changeset-release/main'
        uses: "actions/github-script@v6"
        with:
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0]
            const repository = context.repo

            await github.rest.pulls.merge({
              merge_method: "squash",
              owner: repository.owner,
              pull_number: pullRequest.number,
              repo: repository.repo,
            })
```
