### ISSUE TITLE
`publish` option does not support multiple bash commands

### ISSUE THREAD

**Issue by kachkaev** [changesets/action#225]
\[WIP Issue, I’ll improve the description soon\]

```yaml
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1.3.0
        with:
          publish: echo "hello world" && yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.MACHINE_USER_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

[Related source](https://github.com/changesets/action/blob/8c3f5f5637a95a2327e78d5dabcf357978aedcbb/src/run.ts#L76-L89)

**Comment by lawvs** [comment]
I have the same problem, the action run build cmd but skips publish cmd.

I workaround it by merging the build script and the publish to an npm script.


For more info see https://github.com/lawvs/poi-plugin-quest-2/actions/runs/3262382860/workflow
```yml
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run build && npm publish  # <- the publish script was skipped
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

<details>

```log
No changesets found, attempting to publish any unpublished packages to npm
No user .npmrc file found, creating one
/opt/hostedtoolcache/node/16.17.1/x64/bin/npm run build && npm publish

> poi-plugin-quest-info-2@0.9.2 build
> npm run convertAssets && npm run update

// ...... ...

New Version Detected. Version: [20](https://github.com/lawvs/poi-plugin-quest-2/actions/runs/3262382860/jobs/5359455750#step:5:21)[22](https://github.com/lawvs/poi-plugin-quest-2/actions/runs/3262382860/jobs/5359455750#step:5:23)091101

New Version Detected. Version: 6b8[25](https://github.com/lawvs/poi-plugin-quest-2/actions/runs/3262382860/jobs/5359455750#step:5:26)0e6da4f[38](https://github.com/lawvs/poi-plugin-quest-2/actions/runs/3262382860/jobs/5359455750#step:5:39)9dffcdecdecc72de68f0fe1beb

/usr/bin/git push origin --tags
Everything up-to-date
```

</details>

And the correct output like in here https://github.com/lawvs/poi-plugin-quest-2/actions/runs/3262903759/jobs/5360750330
