### ISSUE TITLE
Publishing does not replace `workspace:*` version

### ISSUE THREAD

**Issue by emmenko** [changesets/action#246]
Hi 👋

I started using the `workspace:` protocol in one of my repos but noticed that when publishing the version didn't get replaced, ending up with a broken release.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/1110551/208677681-5178c86a-0067-418c-94a6-d26121a213cc.png">

Is this a known issue? Is there anything that I'm missing that I need to configure?

Thanks

---

I'm using Yarn v3.

My github action is [configured like this](https://github.com/commercetools/merchant-center-application-kit/blob/e52e8a78228677cad28f1649bc4b1af473308a9a/.github/workflows/release.yml#L43-L56):

```
- name: Creating release pull request or publishing release to npm registry
  id: changesets
  # uses: changesets/action@v1.3.0
  uses: dotansimha/changesets-action@v1.3.3
  with:
    publish: yarn changeset publish
    version: yarn changeset:version-and-format
    commit: 'ci(changesets): version packages'
    createGithubReleases: aggregate
    githubReleaseName: v${{ steps.release_version.outputs.VALUE }}
    githubTagName: v${{ steps.release_version.outputs.VALUE }}
  env:
    GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
    SKIP_POSTINSTALL_DEV_SETUP: true
```

My Changesets config is [configured like this](https://github.com/commercetools/merchant-center-application-kit/blob/main/.changeset/config.json).

**Comment by trivikr** [comment]
Looks like this issue was reported earlier, but no response:
* https://github.com/changesets/action/issues/95
* https://github.com/changesets/action/issues/172

**Comment by Andarist** [comment]
This is being fixed by https://github.com/changesets/changesets/pull/674 - unfortunately, I couldn't find time to finish that work.

**Comment by mkurapov** [comment]
@emmenko does it work if you replace `"package": "workspace:*"` with the actual version of the workspace dependency, ie:   `"package": "workspace:1.0.0"`? Changesets _should_ end up bumping the workspace dependency version automatically when running `changeset version`, e.g. `"package": "workspace:1.0.1"`

**Comment by adesso-os** [comment]
When you specify the actual version number, then that version number is pulled during installation and placed into `node_modules`. Usually, developers don't want that. They want the actual project from the other workspace _linked_ into NM. That is what `workspace:*` provides, but then `changesets` breaks.

**Comment by mkurapov** [comment]
@adesso-os 
> then that version number is pulled during installation and placed into node_modules

This is true for `"package": "1.0.0"`, which will install from the registry, but it _should_ still be linked locally if using the workspace protocol (while specifying a specific version), eg. `"package": "workspace:1.0.0"`. (unless I'm misunderstanding here)

**Comment by unional** [comment]
`workspace:^`

**Comment by arthurfiorette** [comment]
Hey folks! I could get everything working fine by using this custom release script:

```json
"ci:publish": "pnpm publish -r --access public && changeset tag",
```

In case someone actually wants to see it in action:

https://github.com/kitajs/kitajs/blob/e96dc95033e58c9a3a49ab8246ebc085b83a937b/.github/workflows/main.yml#L59
https://github.com/kitajs/kitajs/blob/e96dc95033e58c9a3a49ab8246ebc085b83a937b/package.json#L21

`workspace:^`, dependencies, scoped packages and github releases are working 🙏.

**Comment by arthurfiorette** [comment]
Appearently the above does not works uses the correct dist-tag when publishing...

![image](https://github.com/changesets/action/assets/47537704/93d662be-dc46-4f67-8f05-c9d9325b33c5)

As you can see, the version 4.0.0-next.0 wasn't published with the `next` tag. That's not a problem as you can change this manually with the `npm dist-tag add @kitajs/html@4.0.0-next.0 next` and `npm dist-tag add @kitajs/html@3.1.2 latest` commands

**Comment by mattfysh** [comment]
why does the changeset tool only half-work with the workspace protocol? i.e. bumps during `version` but doesn't support a subsequent `publish`?

**Comment by davtha-aa** [comment]
I am using `yarn@4.5.0` and getting workspace published with `workspace:*`

Installing package that has been published.
```shell
npm i
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*
```

GitHub Action
```yml
- uses: changesets/action@v1
   with:
     version: yarn changeset version
     publish: yarn release
```

My release script in root package.json:
```json
{
   "release": "turbo run build && changeset publish"
}
```

The version PR creation and Publishing works well. Just this last step of `workspace:*` not being resolved to actual versions.
