### ISSUE TITLE
Any way to know if a publish occurred?

### ISSUE THREAD

**Issue by chasemccoy** [changesets/action#25]
I'd like to send a Slack notification whenever a publish happens, but from what I can tell this action doesn't give me any way to determine if it just opened a PR or did a full publish. Maybe I'm missing something? If not, consider this a feature request!

**Comment by Noviny** [comment]
Hi! The publish occurs when the `version` PR is merged, and not before. This is to allow people manual control of when publish happens.

**Comment by chasemccoy** [comment]
@Noviny Yep, I understand that bit... but in the GitHub Action, there’s no way to know which happened so that I can conditionally run a script if it was a publish. I don’t want the script to run every time the action updates the PR.

**Comment by mitchellhamilton** [comment]
The `publish` command that's passed to the action only runs on publishes so you can run a script there

**Comment by chasemccoy** [comment]
@mitchellhamilton Yeah I can do that, was just hoping to use a GitHub Action for this to make it easier! Thanks!

**Comment by ocavue** [comment]
We can use GitHub Actions' `outputs` feature to implement this.

Docs: https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions#outputs

**Comment by ocavue** [comment]
I wrote a simple prototype #26 .

**Comment by chasemccoy** [comment]
This is exactly what I had in mind. Thanks @ocavue!

**Comment by ocavue** [comment]
> The `publish` command that's passed to the action only runs on publishes so you can run a script there

@mitchellhamilton 

It seems that's not true. When there is nothing to publish, this action will still run `publish` command. In my case, the command is `yarn run changeset publish`, which will not throw an error even when there is nothing to do so the CI itself does pass.

Check this example: https://github.com/ocavue/my-test-package/runs/599742337#step:8:14

```
$ changeset publish
🦋  info npm info @ocavue/my-test-package
🦋  warn @ocavue/my-test-package is not being published because version 2.0.1 is already published on npm
🦋  warn No unpublished packages to publish
```

**Comment by chasemccoy** [comment]
This is awesome. Thanks so much for tackling this @ocavue!

**Comment by ocavue** [comment]
You're welcome.

**Comment by chasemccoy** [comment]
@ocavue I am having some trouble accessing the `publishedPackages` output in my Action... here's what I'm trying to do:

```
- name: Slack notification on publish
        if: steps.changesets.outputs.published == 'true'
        uses: Ilshidur/action-slack@master
        with:
          args: "We just published ${{steps.changesets.outputs.publishedPackages[0].name}} ${{steps.changesets.outputs.publishedPackages[0].version}}."
```

But this doesn't seem to work. Am I accessing the output correctly? Do I need to parse the JSOn string first, and if so, how?

**Comment by chasemccoy** [comment]
Looks like maybe the `toJSON` function is what I am looking for: https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#tojson

**Comment by ocavue** [comment]
All outputs returned by github action steps are *string*. You can't do `publishedPackages[0]` to a string.

You can write a script with js/python to parse a JSON string. Or you can use [jq](https://stedolan.github.io/jq/), which should be already installed inside the github actions environment, to parse a JSON string within bash.

**Comment by ocavue** [comment]
@chasemccoy 

I wrote a simple example for `jq`: https://github.com/ocavue/my-test-package/runs/636813963#step:12:8

**Comment by chasemccoy** [comment]
@ocavue Hmm... `jq` doesn't seem to be defined in my action...

**Comment by ocavue** [comment]
As far as I know, there are some cases that you don't get `jq` in your environment:

- you are not using ubuntu environment
- you are using self-host GitHub actions environment
- you are using docker 
- you are using wrong action syntax

However, as I said above, jq is not necessary. You just need a method to **parse** a JSON **string** into a JSON **object**.

Maybe you need an extra action step to do the parse job.

I can do some help if you need it and your repo is not private.

**Comment by chasemccoy** [comment]
@ocavue Thanks for the help! The repo is private, but here's what I have in my action just to test this:

```
name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Test
        id: changesets
        run: echo "::set-output name=publishedPackages::'[{name:'Racine',version:'5'}]'"
      - name: Get published package version
        id: version
        run: |
          VERSION=$(echo $changeset_outputs_published_packages | jq '.[0].version')
          echo "::set-output name=version::$VERSION"
        env:
          changeset_outputs_published_packages: ${{ steps.changesets.outputs.publishedPackages }}
      - name: Test
        run: echo ${{ steps.version.outputs.version }}
```
