### ISSUE TITLE
Custom pull request title

### ISSUE THREAD

**Issue by JasperAlexander** [changesets/action#274]
How to change the default pull request title?

**Comment by tiborsaas-tw** [comment]
+1 on this,

This breaks our PR-s by default because we have criteria for minimal length.

**Comment by timbonicus** [comment]
You can specify `title` as part of the action config:

```yaml
      - name: Changesets PR or publish
        uses: changesets/action@v1
        with:
          title: My Custom PR title
```
