### ISSUE TITLE
Action not started after PR merged

### ISSUE THREAD

**Issue by 1xtr** [changesets/action#276]
I have simple workflow:

```
on:
  push:
    branches:
      - production
```

Today I create PR and merge it, and action not started.

2 days ago all worked
