### ISSUE TITLE
Action failing at logger error

### ISSUE THREAD

**Issue by earlAchromatic** [changesets/action#297]
NPM token is an automation one.

release.yaml

```
name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm i

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

```

<details>
<summary>Log</summary>

```
created ./dist/index.mjs, ./dist/index.js in 1s
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:905:11)
    at Socket._write (node:net:917:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Socket.Writable.write (node:internal/streams/writable:336:10)
    at console.value (node:internal/console/constructor:299:16)
    at console.log (node:internal/console/constructor:376:26)
    at Object.info (/home/runner/work/notion-cms/notion-cms/node_modules/@changesets/logger/dist/logger.cjs.dev.js:21:11)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Error: Error: The process '/opt/hostedtoolcache/node/16.20.0/x[64](https://github.com/agency-kit/notion-cms/actions/runs/5011148029/jobs/8981677193#step:6:65)/bin/npm' failed with exit code 1
Error: The process '/opt/hostedtoolcache/node/16.20.0/x64/bin/npm' failed with exit code 1
```
</details>

Repo: https://github.com/agency-kit/notion-cms
