### ISSUE TITLE
fix: trying to publish when not needed

### ISSUE THREAD

**Issue by jjangga0214** [changesets/action#300]
```yaml
      - name: Create Release PR or Publish
        uses: changesets/action@v1
        id: changesets
        with:
          commit: 'chore: release'
          title: 'chore: release'
          version: pnpm changeset version
          publish: 'pnpm -r publish && changeset tag && git push --follow-tags'
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

It executes `publish` when it should not. 

<img width="1123" alt="스크린샷 2023-06-08 오후 6 39 09" src="https://github.com/changesets/changesets/assets/28584151/ffb139ed-9dcf-46bf-ae76-4832a3027c1a">

Currently in my repo, as the printed messages suggest, there's no changeset and nothing new to release.
So it should not publish, but it tries running the command `'pnpm -r publish && changeset tag && git push --follow-tags'` which I set as `publish` option.
