### ISSUE TITLE
Custom Pull request title with tag version

### ISSUE THREAD

**Issue by AdisonCavani** [changesets/action#303]
I'd like to get a customized Pull request title / commit message like this: `release: v0.0.1`.

I know there is ability to customize the title:

```yml
      - name: Changesets PR or publish
        uses: changesets/action@v1
        with:
          title: My Custom PR title
``` 

But I want to also get a tag name, so the naming in more specific.
Is this possible?

**Comment by denizdogan** [comment]
Did you figure this out? I'm looking for the same thing.

**Comment by lakardion** [comment]
I would love to know as well how I can add the version to the PR title

**Comment by r115** [comment]
I have a customized hack for it. There is a PR somewhere here for adding a --dry-run flag which should solve this. Anyway, here's my hack;

Context
---
- monorepo using pnpm
- custom helper file at the root project
- only creating a pull request. no package is published
- single changeset per action


Steps
---
#### Create helper file at project root
```javascript
const config = require('./release.json');
const {unlink} = require('fs')

const commit_message = `v${config.releases[0].newVersion} of ${config.releases[0].name}`
unlink('./release.json', () => {})

console.log(commit_message)
```
#### Add a step to generate changeset
```yaml
steps:
  ...
  - name: Prep commit message
     id: prep_commit_message
     run: |
       MESSAGE=$(pnpm changeset status --output=./release.json && node release-helper.js | tail -n 1)
       echo "message=${MESSAGE}" >> $GITHUB_OUTPUT
```

#### profit
````yaml
steps:
  ...
  - name: Create Release Pull Request
     uses: changesets/action@v1
     with:
       title: ${{ steps.prep_commit_message.outputs.message }}
       commit: "release version ${{ steps.prep_commit_message.outputs.message }}"
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
````


-----
This stuff can possibly be knocked out with a one liner using `jq`. Just didn't want to jump through the hoops until the solution works over some time.

**Comment by hollandjake** [comment]
Incase you are ever interested in the jq version - @r115 

It creates a release.json file temporarily extracts the version using jq and then removes the file (this is due to an outstanding feature request https://github.com/changesets/changesets/issues/1020)

```yaml
steps:
  ...
  - name: Prep commit message
    run: |
      echo "NEW_VERSION=$(pnpm changeset status --output=release.json && jq -r '.releases[0].newVersion' release.json && rm release.json)" >> "$GITHUB_ENV"
  - name: Create Release Pull Request or Publish
    id: changesets
    uses: changesets/action@v1
    with:
      title: "Release v${{env.NEW_VERSION}}"
      commit: "Release v${{env.NEW_VERSION}}"
      publish: pnpm run release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

**Comment by dcroote** [comment]
@hollandjake this is excellent, thanks

**Comment by jpconnol** [comment]
Leaving here in case it helps anyone else, @hollandjake's script above is incredible and saved me a ton of time but was also capturing the output of the `pnpm changeset status --output=release.json` which was something like: 

```
> @your-repo changeset /Users/path
> changeset "status" "--output=release.json"
```

To reconcile, I had to adjust it ever so slightly to ensure that we only captured the new version number itself:

```yaml
- name: Capture New Release Version
  run: |
    pnpm changeset status --output=release.json
    echo "NEW_VERSION=$(jq -r '.releases[0].newVersion' release.json)" >> "$GITHUB_ENV"
    rm release.json

- name: Create Release Pull Request or Publish
  id: changesets
  uses: changesets/action@v1
  with:
    title: "Release v${{env.NEW_VERSION}}"
    commit: "Release v${{env.NEW_VERSION}}"
    publish: pnpm run release
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
 ```
