### ISSUE TITLE
Skip the PR process

### ISSUE THREAD

**Issue by origranot** [changesets/action#310]
Hey,

Is it possible to skip the automated PR created by this action? Is there a flag we can pass to automatically push changes to master and do the release?

**Comment by gabrielalmeida** [comment]
I was also looking for this. Duplicated of #77 and #215.

**Comment by JamilOmar** [comment]
you can use this action I created:
https://github.com/JamilOmar/autopublish-changesets-action

**Comment by mogeko** [comment]
I believe I've found the solution!

First, go to the Repo's Settings -> General -> Pull Request -> Open the 「Allow auto-merge」[Learn more](https://docs.github.com/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request).

<img width="794" alt="Image" src="https://github.com/user-attachments/assets/cc1b5abe-7d6f-4679-a47a-b9d29e4e19c3" />

Then, add the following to the workflow file:

``` yaml
steps:
  # ...
  - name: Create Changesets PR or Publish to NPM
    id: changesets
    uses: changesets/action@v1.4.10
    with:
      commit: "chore(release): version packages"
      title: "chore(release): version packages"
      version: pnpm vite-node .github/changeset-version.ts
      publish: pnpm changeset publish
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_ENV: "production"

  - name: Enable auto-merge for Changesets PRs
    if: steps.changesets.outputs.hasChangesets
    run: gh pr --repo "$REPO" merge --auto --merge "$PR_NUM"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUM: ${{ steps.changesets.outputs.pullRequestNumber }}
      REPO: ${{ github.repository }}
```

The effect is as follows:

<img width="925" alt="Image" src="https://github.com/user-attachments/assets/b2677f7f-9c35-4e38-b7ef-8551e5b36a16" />

Issues: #77 #215
