### ISSUE TITLE
problem with outputs object

### ISSUE THREAD

**Issue by ah7255703** [changesets/action#319]
i am trying to upload the build directory (dist) as artifact 
**NOTE**: it is only one package. 
```yml 
      - name: Upload embed as artifact.
        uses: actions/upload-artifact@v3
        if: ${{ steps.changesets.outputs.published }}
        with:
          name: my-package@${{steps.changesets.outputs.publishedPackages[0].version}}
          path: search-widget/dist
```
the result is my-package@
