### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by magnusriga** [changesets/action#323]
Hi,

I am running this action, with the below workflow.

It crashes at the `actions/cache@v3` point. See error screen shot below.

**Any idea what is wrong here?**

```yml
name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  NODE_LTS_VERSION: latest

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
          check-latest: true

      - name: Install pnpm globally
        run: npm i -g pnpm@${PNPM_VERSION}

      - name: Save pnpm store path
        id: get-store-path
        run: echo STORE_PATH=$(pnpm store path) | tee -a $GITHUB_OUTPUT
        # run: echo STORE_PATH=$(pnpm store path) >> $GITHUB_OUTPUT

      - name: Restore pnpm from cache (using saved path)
        uses: actions/cache@v3
        timeout-minutes: 5
        id: cache-pnpm-store
        with:
          path: ${{ steps.get-store-path.outputs.STORE_PATH }}
          key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-
            pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install package.json dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Create pull request with updated package versions and changelogs (i.e. runs changeset version)
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        # This expects you to have a script called release which does a build for your packages and calls changeset publish
        # Build not necessary if not publishing to npm, in which case publish is only to add git tags
        # publish: pnpm release

      # If pushing to main (manually, or at PR merging), add tags (publish) if no changesets present.
      # We block committing to main, and force changesets when creating a feature PR,
      # so only time we push PR without changesets is when merging PR created automatically by changeset's GH Action.
      # Thus, below only runs when we merge auto created changeset PR into main where "changeset version" has already been run.
      - name: Publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: pnpm release

      - name: Send a Slack notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        # You can do something when a publish happens.
        run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
```

![image](https://github.com/changesets/action/assets/38915578/d60f54d9-9a52-460c-a1f1-cc0ff27e92b8)
