### ISSUE TITLE
action formatting package.json in wrong way

### ISSUE THREAD

**Issue by technophile-04** [changesets/action#366]
### Description : 

When the "Version Packages" PR is created it updates the package.json version but also formats other fields in the wrong way. 

![Screenshot 2024-04-28 at 10 41 30 PM](https://github.com/changesets/action/assets/80153681/4639094e-ec53-414f-b5df-6a0f56fe9421)

It's not respecting my biome.json config and instead I think its using prettier to format the file

**Comment by errmayank** [comment]
Found a way to fix this, in the action's "Create a release pull request" step you can add a custom script using [version](https://github.com/changesets/action?tab=readme-ov-file#with-version-script)

BUT it fails for some reason if you add the format script right there, like if you do this


```yaml
# release.yml

- name: "Create a release pull request"
  uses: changesets/action@v1
  with:
    commit: "chore(release): version packages"
    title: "chore(release): version packages"
    version: pnpm changeset version && pnpm format
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```


So instead create a separate script that does both and add it there

```jsonc
/* package.json */

  "scripts": {
    "format": "prettier --write \"**/*.{svelte,js,cjs,mjs,ts,cts,mts,json,md,yaml,yml}\"",
    "changeset-add": "changeset add",
    "changeset-status": "changeset status --verbose",
    "changeset-version": "changeset version && pnpm format"
  },
```
```yaml
# release.yml

- name: "Create a release pull request"
  uses: changesets/action@v1
  with:
    commit: "chore(release): version packages"
    title: "chore(release): version packages"
    version: pnpm changeset-version
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
