### ISSUE TITLE
Github action setup question

### ISSUE THREAD

**Issue by ryanbas21** [changesets/action#386]
I want to make sure I understand this correctly. My goal is for changesets to have this flow

feature branch -> merge develop -> create pr against master -> merge to master releases to npm.

```yaml
on:
  push:
    branches:
      - develop
      - master
      
      ....rest of setup
     - name: publish
        uses: changesets/action@v1
        with:
          publish: pnpm release-packages ## command in root package.json that builds and publishes
          title: Release PR
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
```

is this correct? I read a few issues and saw the PR that added the `branch` to it. the description of the config setting wasn't entirely clear to me though.
