### ISSUE TITLE
Does not update existing PR: A pull request already exists for

### ISSUE THREAD

**Issue by edouardr** [changesets/action#396]
Since the latest version (v1.4.8) I get an error when a changesets PR already exists.

see the output log

```
 delete mode 100644 .changeset/wise-nails-wave.md
 create mode 100644 apps/new_file.md
 create mode 100644 apps/my-package/CHANGELOG.md
 create mode 100644 packages/another-package/CHANGELOG.md
/usr/bin/git push origin HEAD:changeset-release/main --force
To https://github.com/MyOrg/MyRepo
 + 4cd5cdb...8c05ff1 HEAD -> changeset-release/main (forced update)
[]
creating pull request
Error: HttpError: Validation Failed: {"resource":"PullRequest","code":"custom","message":"A pull request already exists for MyOrg:changeset-release/main."}
Error: Validation Failed: {"resource":"PullRequest","code":"custom","message":"A pull request already exists for MyOrg:changeset-release/main."}
```

If we pay attention we can see that we have `creating pull request` instead of `updating found pull request #A_NUMBER`.

It seems this would have been introduced by this commit https://github.com/changesets/action/commit/48ab0d2f2e77ae169182d022591ef5c18c931ff2, as we can see `[]` in the output just before.

This would come from:

```
/// src/run.ts l.381
 let existingPullRequests = await existingPullRequestsPromise;
  core.info(JSON.stringify(existingPullRequests.data, null, 2));
```

**Comment by Andarist** [comment]
Cc @s0

**Comment by Andarist** [comment]
Weirdly, I see pull requests to be updated just fine using the recent version, for example [here](https://github.com/statelyai/xstate/actions/runs/10602381277/job/29384287928). 

If we take a close look we can see a lone `[]` a line above `creating pull request`. I believe this comes from this line:
https://github.com/changesets/action/blob/50750fa876cc1e54c7cb972db5e2f7271fc53d99/src/run.ts#L382

So the response the action got to this request was, indeed, an empty array - indicating that there are no open PRs there. How many do u have? Could you try to programmatically query the same thing as [here](https://github.com/changesets/action/blob/50750fa876cc1e54c7cb972db5e2f7271fc53d99/src/run.ts#L345-L350) and report what result do u get back?

**Comment by s0** [comment]
Is there any chance that there were multiple workflows being run concurrently that interfered? And what happens when you try to re-run the workflow run, is it consistently doing the same thing?

**Comment by Andarist** [comment]
> One potential solution could be to just

OTOH, if this is a race condition this might be a good thing that it fails. It lets the user to correct their `concurrency` setting.

**Comment by edouardr** [comment]
Hi guys!

Thanks for the answers. So to let you know, I reverted the action to this commit: aba318e9165b45b7948c60273e0b72fce0a64eb9

```
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@aba318e9165b45b7948c60273e0b72fce0a64eb9
        with:
          version: pnpm run ci:version
          commit: 'chore(twinops): update versions'
          title: 'chore(twinops): update versions'
          publish: pnpm run ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GPR_ACCESS_TOKEN }}
```

This successfully updated the existing PR

```
 {
  "total_count": 1,
  "incomplete_results": false,
  "items": [
    {
    /// ...

updating found pull request #66
```

Tonight, I'll run 
```
 let existingPullRequests = await existingPullRequestsPromise;
  core.info(JSON.stringify(existingPullRequests.data, null, 2));
```

To see what the result is.
