### ISSUE TITLE
Make it possible to create a GH release without publishing!

### ISSUE THREAD

**Issue by trueberryless** [changesets/action#422]
## Description

I'm currently struggling to create a nice CI flow because this action doesn't want to create a release when no publishing happens. I would love to use this action for versioning my website too, which unfortunately is no npm package and therefore things are very very complicated when I want to work with this action. But I love this approach and this action, so I'm gonna ask if it is possible to adapt the action, so it supports creating a release, even when no publishing happens. This would allow to create a custom GH action for deploying and this action handles the releases as soon as the deployment succeeds.

I was thinking of something like this: When the user specifically enables `createGithubReleases`, the action creates it as if a publish happend. I'm not sure how much of a refactor this would be for this action, but let's discuss possible solutions below!

```yaml
release:
        name: Release
        needs: deployment
        runs-on: ubuntu-latest
        outputs:
            docs: ${{ steps.changesets.outputs.hasChangesets }}
        steps:
            - # ...
            - name: Create Release Pull Request
              id: changesets
              uses: changesets/action@v1
              with:
                  createGithubReleases: true
              env:
                  GITHUB_TOKEN: ${{ secrets.PUBLIC_GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

## Related Issue

https://github.com/changesets/changesets/issues/849

**Comment by Nickersoft** [comment]
I'm interested in this as well! I feel like it should be fairly straightforward to add, so happy to open a PR if the maintainers think it's a good idea :) Also, I think maybe it would make more sense to either let `publish` be an optional arg, or have a `skipPublish` option in the config. 

What I find odd is that this action literally uses regex to grep the output of your `publish` command to figure out the tags it should publish. I would think that seeing Changesets itself is a versioning tool, it should be able to just invoke a CLI command that would provide the latest version numbers. We might have to add that though, not sure.

**Comment by Sampm91** [comment]
I'm Email address for you

در تاریخ شنبه ۱۶ نوامبر ۲۰۲۴،‏ ۱۰:۰۹ Tyler Nickerson <
***@***.***> نوشت:

**Comment by Sampm91** [comment]
The academy to app your.all time is working and app your why don't you have
my! my canect is and app your.plaez the dissent your don't me🙏🙏🙏

در تاریخ شنبه ۱۶ نوامبر ۲۰۲۴،‏ ۱۰:۱۸ حسین پنجه مریم ***@***.***>
نوشت:

**Comment by trueberryless** [comment]
> Also, I think maybe it would make more sense to either let `publish` be an optional arg, or have a `skipPublish` option in the config. 

I think that the publish command is currently optional, however if it is not provided, the axtion assumes you don't want to publish which automatically means that you don't want to release anything. That's the problem...

**Comment by Nickersoft** [comment]
Ah you're right @trueberryless – in that case I would think your original intuition is probably correct. Explicitly setting a GitHub release flag would trigger a release regardless of whether `publish` is specified or not. Otherwise, I would think the `createGitHubRelease` flag _default_ would only apply if `publish` is also being specified.

**Comment by trueberryless** [comment]
> Otherwise, I would think the `createGitHubRelease` flag _default_ would only apply if `publish` is also being specified.

That is THE PERFECT SOLUTION in my mind, but we also have to think about the flaws: It's very unintuitive for newcomers and complicated to explain in documentation because different props kinda chnage the logic of each other without changing the other prop. 

So maybe an additional prop would be more beneficial...

**Comment by trueberryless** [comment]
I have for now solved this issue by using external create release actions, namely [`ncipollo/release-action@v1`](https://github.com/ncipollo/release-action), together with some additional actions, like [`Ilshidur/action-discord@0.3.2`](https://github.com/Ilshidur/action-discord), and reading the package version manually.

```yaml
name: Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  changesets:
    name: Changesets
    runs-on: ubuntu-latest
    outputs:
      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "[ci] release" // could be removed depending on #426 
          title: "[ci] release" // could be removed depending on #426 
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  image-tag:
    name: Image Tag
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ env.IMAGE_TAG }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Read version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' docs/package.json)
          echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV

  deployment:
    needs: [changesets, image-tag]
    if: >
      (
        needs.changesets.outputs.hasChangesets == 'false' && 
        (
          contains(github.event.head_commit.message, 'deploy') || 
          contains(github.event.head_commit.message, '[ci] release')
        )
      ) || 
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          package_json_file: ./docs/package.json

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install
        shell: bash
        working-directory: ./docs

      - name: Build Website
        run: pnpm run build
        shell: bash
        working-directory: ./docs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ needs.image-tag.outputs.IMAGE_TAG }}
            ${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update deployment.yaml file
        run: |
          yq eval '.spec.template.spec.containers[0].image = "${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ needs.image-tag.outputs.IMAGE_TAG }}"' -i manifest/deployment.yaml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update deployment.json container image (automated)

  release:
    name: Release
    needs: [image-tag, deployment]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - id: extract-changelog
        uses: sean0x42/markdown-extract@v2.1.0
        with:
          file: docs/CHANGELOG.md
          pattern: ${{ needs.image-tag.outputs.IMAGE_TAG }}

      - uses: ncipollo/release-action@v1
        id: create_release
        with:
          tag: ${{ env.IMAGE_NAME }}-docs@${{ needs.image-tag.outputs.IMAGE_TAG }}
          makeLatest: false
          body: ${{ steps.extract-changelog.outputs.markdown }}
          skipIfReleaseExists: true

      - name: Check if release was created
        id: check_release
        run: |
          if [ -z "${{ steps.create_release.outputs.html_url }}" ]; then
            echo "RELEASE_SKIPPED=true" >> $GITHUB_ENV
          else
            echo "RELEASE_SKIPPED=false" >> $GITHUB_ENV
          fi

      - name: Discord notification
        if: env.RELEASE_SKIPPED == 'false'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            # ${{ env.IMAGE_NAME }}@${{ needs.image-tag.outputs.IMAGE_TAG }}

            ${{ steps.extract-changelog.outputs.markdown }}
```

[Reference](https://github.com/trueberryless-org/starlight-cooler-credit/blob/b1f1d2cabe63369aac65461d5adb99403a6ee892/.github/workflows/deployment.yaml)

This gives me much more freedom in general because I can even sent notifications to discord and have the image tag available everywhere.

Nonetheless, I think that the `createGitHubRelease` flag / input would be able to improve and simplify my action and simplify many other use cases even more, so I'm gonna keep the issue open for now...
