### ISSUE TITLE
Parameter expansion doesn't appear to work in `publish` command

### ISSUE THREAD

**Issue by steveluscher** [changesets/action#444]
I have [the following config](https://github.com/anza-xyz/kit/blob/e36cfbff8f5447446d31d8ef349365073db79602/.github/workflows/publish-packages.yml#L45-L53):

```yaml
      - name: Create Changesets Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm turbo publish-packages --concurrency=${TURBO_CONCURRENCY:-1}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PUBLISH_TAG: next
```

The `${TURBO_CONCURRENCY:-1}` parameter expansion does not seem to work. I received the error: 

```
/home/runner/setup-pnpm/node_modules/.bin/pnpm turbo publish-packages --concurrency=${TURBO_CONCURRENCY:-1}
  x Invalid value for `--concurrency` flag. This should be a positive integer
  | greater than or equal to 1: ${TURBO_CONCURRENCY:-1}
```

I believe this must be because `--concurrency` was passed the _literal_ value `${TURBO_CONCURRENCY:-1}` instead of the _result_ of the parameter expansion (ie. `1`).
