### ISSUE TITLE
Cannot get changesets version to format after versioning

### ISSUE THREAD

**Issue by ryanbas21** [changesets/action#470]
I have tried many ways of versioning and formatting code so my CI is happy but I cannot for the life of me get it to respect this.

```
"ci:release": "pnpm publish -r --no-git-checks && changeset tag",
"ci:version": "changeset version && pnpm install --no-frozen-lockfile && pnpm nx format:write",
```

is my current implementation, but I've tried putting the format command in a script and calling it there also.

basically it seems to never respect formatting, is there something I'm missing on this? i can provide more information if needed.

**Comment by Andarist** [comment]
Are you using `changesets/action` like this?
```yml
- uses: changesets/action@v1
  with:
    version: pnpm run ci:version
```

**Comment by ryanbas21** [comment]
@Andarist Correct. This is what the step in my GH actions workflow looks like

```
 - name: publish
        uses: changesets/action@v1
        id: changesets
        with:
          publish: pnpm ci:release
          version: pnpm ci:version
          title: Release PR
          branch: main
          commit: 'chore: version-packages'
          setupGitUser: true
```
