### ISSUE TITLE
Remove usage of `process.chdir()`

### ISSUE THREAD

**Issue by s0** [changesets/action#475]
See: https://github.com/changesets/action/pull/473#discussion_r2081314357

As of #473, we now explicitly set the `cwd` argument for all subprocess calls. As such, it shouldn't be necessary to change the working directory of the current process.

We need to ensure that usage of `commitChangesFromRepo` (which makes a call to `process.cwd()`) also works correctly for our use-cases before we can remove this process call.

Namely, we need a way for running this action to work when:

- a repository is checked-out into a sub-directory.
- `cwd` is set to a subdirectory of that subdirectory

In particular, we should:

* Update `commitChangesFromRepo` so that `repoDirectory` can be used to recursively start a search for the root of a repository.
* Specify `repoDirectory` to be explicit `cwd`, as with `addFromDirectory`.

**Comment by ikovic** [comment]
Hi! I'm hoping this could be useful input for this - today we noticed that our CI has been broken since the [1.5.2 release](https://github.com/changesets/action/releases/tag/v1.5.2).

This is our job definition:
```
      - name: Create and publish versions
        uses: changesets/action@v1
        with:
          cwd: web/sdk
          publish: yarn publish:ci
        env:  // omitted
```

The package we're managing using `changesets` is in `web/sdk` and since this release this action has been failing consistently with this message:
```
Run changesets/action@v1
  with:
    cwd: web/sdk
    publish: yarn publish:ci
    setupGitUser: true
    createGithubReleases: true
    commitMode: git-cli
  env:
    GITHUB_TOKEN: ***
    NODE_AUTH_TOKEN: ***
    NPM_TOKEN: ***
changing directory to the one given as the input
setting git user
/usr/bin/git config user.name "github-actions[bot]"
Error: Error: The cwd: web/sdk does not exist!
Error: The cwd: web/sdk does not exist!
```

I am not in a position to debug this but my assumption is that since we ran `cwd` [once already](https://github.com/changesets/action/blob/3c24abeab26da6335c181222faa2ea485a092cf8/src/index.ts#L21) we might already be in the specified dir when running `git.setupUser` so the second time the dir is not found.

Two questions come to mind:
- is there anything we could change in the config to circumvent this behaviour for now?
- is this a bug? Eg is our setup different from the baseline?

Thanks and please let me know if I can help.

**Comment by s0** [comment]
Ah okay i see what's causing this, @Andarist it's due to `cwd` being a relative path, so we can't actually set it for any of the exec calls, as it will try to set it from within the `cwd`. Removing process.chdir will fix this 😅

**Comment by s0** [comment]
We could also use path.resolve() before we use the arg value, but we may as well just remove the call like outlined above.

**Comment by Andarist** [comment]
> is there anything we could change in the config to circumvent this behaviour for now?

You could set it to a non-relative path.

> We could also use path.resolve() before we use the arg value, but we may as well just remove the call like outlined above.

I'd say we should do it regardless of the `process.chdir()` removal.

**Comment by oshytiko** [comment]
Broke our builds as well!

Using absolute path helped, but it took for us some time to find this PR.

At least update README that it should be an absolute path and give an example how to achieve that (something like that):

```
    - name: Create Release Pull Request
      if: github.ref == 'refs/heads/main'
      id: changesets
      uses: changesets/action@v1
      with:
        cwd: "${{ github.workspace }}/packages/${{ env.APP_NAME }}"
        title: "chore(${{ env.APP_NAME }}): version package"
        commit: "chore(${{ env.APP_NAME }}): version package"
```
