### ISSUE TITLE
Action closes existing version PR

### ISSUE THREAD

**Issue by jacksonneal** [changesets/action#487]
We've discovered what we believe is a bug in v1.5.2.  We are using changesets with the following config:

```
      - id: changesets
        uses: changesets/action@v1.5.2
        with:
          publish: pnpm run publish
          setupGitUser: false
          commitMode: github-api
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
```

This works fine if there is no current "Version Packages" PR open as it will create one.  But if I merge additional changefiles to main, the action will close the "Version Packages" PR and then correctly push the update version and changelog.  The workaround is to manually reopen the PR or downgrade the action version.  This is not an issue in v1.5.1.

Possibly related to this change: https://github.com/changesets/action/pull/473.

cc @jackheinemann
