### ISSUE TITLE
`commitMode: github-api` does not work

### ISSUE THREAD

**Issue by alexaka1** [changesets/action#494]
I have migrated to the new commit mode, however it is not working.

I merged this PR https://github.com/alexaka1/distroless-dotnet-healthchecks/pull/533 which was empty (already a red flag), but then a new one was just created, also empty https://github.com/alexaka1/distroless-dotnet-healthchecks/pull/534

I don't know what I'm doing wrong, the git commit mode used to work fine, but I was really excited to use the new signed commits version.

This is the workflow that used to work perfectly with the old method, but does not work with the new commit mode. https://github.com/alexaka1/distroless-dotnet-healthchecks/blob/main/.github%2Fworkflows%2Fversion.yml

I know about #487 that is not my concern now, but this commit mode does not seem to work.

I don't think it's a permission issue, as no logs are produced and these look fine to me  
```yaml
    permissions:
      pull-requests: write
      contents: write
      issues: read
      id-token: write
```
