### ISSUE TITLE
Adding label to PR

### ISSUE THREAD

**Issue by williamboman-pp** [changesets/action#50]
Hey. We'd like to be able to automatically add a label to the PR that gets created, is this possible somehow?

**Comment by Andarist** [comment]
Seems like this might be highly specific to a particular project - you could automate this using other github actions or by creating a dedicated probot app for this.

**Comment by williamboman-pp** [comment]
Hmm I see. Do you mean something like https://github.com/actions/labeler? Personally I don't feel like wanting to have labels on Changeset PRs is an uncommon use case, I think it'd be nice to have "all batteries included".

But seeing how easy it is to compose actions, maybe that's a better approach.

**Comment by denieler** [comment]
we used `actions/github-script@v4` action for this, works pretty fine and easy to setup:

```
- name: Add label to "Version Package" PR
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // Get list of all open PRs with
            // head branch "changeset-release/master"
            // (there should be max 1 PR with such condition)
            const { data } = await github.pulls.list({
              owner: 'owner',
              repo: 'repoName',
              state: 'open',
              head: `{repoName}:changeset-release/master`
            })

            for await (let pr of data) {
              github.issues.addLabels({
                owner: 'owner',
                repo: 'repoName',
                issue_number: pr.number,
                labels: [
                  'some-label'
                ]
              })
            }
```

**Comment by BeeeQueue** [comment]
Alternatively you could also use the GitHub CLI which is available in all actions:

```yml
jobs:
  label:
    name: Adds labels to PRs
    steps:
      - run: gh pr edit --add-label "label name" "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # Not sure if this one is required
```

**Comment by Andarist** [comment]
> Alternatively you could also use the GitHub CLI which is available in all actions:

TIL, nice!

With that in place - it really feels like something that can be handled externally. We could use a "recipe" for this in the README though if anyone wants to prepare one.

**Comment by quantizor** [comment]
I have a use case where it would be helpful if this was just part of the changesets action.

Specifically I'd like to add an "automerge" label if the changeset only contains patch changes. Would use it like this:

```yml
- name: Check for Patch Changes
  id: check_patch
  run: |
    if yarn changeset status | grep -q "info Packages to be bumped at patch"; then
      echo "::set-output name=label::automerge"
    else
      echo "::set-output name=label::"
    fi

- name: create or publish changeset
  id: create-or-publish-changeset
  uses: changesets/action@v1
  env:
    GITHUB_TOKEN: [redacted]
  with:
    commit: "chore: update package version"
    label: ${{steps.check_patch.outputs.label}}
    publish: "yarn release"
    setupGitUser: false
    title: "chore: update package version"
```
