### ISSUE TITLE
project's .npmrc not respected

### ISSUE THREAD

**Issue by kamleshchandnani** [changesets/action#58]
Right now if you have an `.npmrc` at the project root that is not respected but rather the following piece of code just checks the `.npmrc` in the HOME directory

https://github.com/changesets/action/blob/cd904b92c71a9cde409529b9eb7bf7fd05ea5858/src/index.ts#L44-L53

Even the ideal flow for npm or any process is they check for `.npmrc` at the project root if not then they look for `.npmrc` in the HOME directory.

**Comment by talves** [comment]
I don't think this `.npmrc` is even being used by changesets.

I had to replace my `env.NPM_TOKEN` with `env.NODE_AUTH_TOKEN` because I'm using `actions/node-setup` and changesets is working fine without the `NPM_TOKEN`.

**Comment by talves** [comment]
**Update Explanation:** `actions/setup-node` creates an auth file when the registry-url exists and uses `NODE_AUTH_TOKEN` then puts that path in the `NPM_CONFIG_USERCONFIG` environment variable.  I believe this now overrides the use of the .npmrc file and why it's not used.

I wonder if `changesets/action` should maybe check for `NPM_CONFIG_USERCONFIG` existing before it writes out the `.npmrc` file and/or log out an explanation.

Maybe someone can explain if this is true or clear up any misunderstanding.

**Comment by medihack** [comment]
I also stumbled upon this. My repository uses a `.npmrc` which is simply ignored by this action and overwritten. Would be nice to check for this, too.

**Comment by nikparo** [comment]
For a CI action to be hard-coded to only check `$HOME/.npmrc` is pretty bad imo. At least self-hosted runners are often stateful, and potentially concurrent, so adding files to a shared directory should be avoided. Especially since the action doesn't clean up after itself.

As a workaround I opted to change the `$HOME` variable during the run. Not ideal, but it appears to work just fine. If someone knows how to set $HOME using [jobs.steps.env](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv), then that would be even better.

```yaml
  # changesets/action presumes the .npmrc is in $HOME
  # See:
  # - https://github.com/changesets/action/issues/58
  # - https://github.com/changesets/action/blob/2bb9bcbd6bf4996a55ce459a630a0aa699457f59/src/index.ts#L58
  - name: Set HOME
    run: echo "HOME=$(pwd)" >> $GITHUB_ENV
```
