### ISSUE TITLE
updating Version Packages PR uses GITHUB_TOKEN instead of PAT

### ISSUE THREAD

**Issue by emilgp** [changesets/action#70]
**Background**

We have this running in master.yml
```
      - id: changesets
        uses: changesets/action@master
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        ....
```

We also have a separate pull_request.yml that runs the usual lint and test status checks before it can be merged

When we used `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` before the PR action is not being triggered, so we had to use PAT. Now after a successful changeset merge it will create a new Version Packages PR and trigger the PR Action.

**Problem**

After a changeset merge with an existing Version Packages PR, the changes are pushed into the Version Packages PR correctly, however it is not triggering the action (git push is using GITHUB_TOKEN again)

Anyone found a way to have that git push use PAT as well?

Thanks

**Comment by Andarist** [comment]
Could you describe in more detail which part of the workflow is not using the PAT? I'm a little bit confused considering the given description.

**Comment by emilgp** [comment]
Hi @Andarist, 
```                
            feature/b 
    feature/a     \
        \          \
master --A1---------B1--
          \          \
version    A2---------B2--
```
A1 and B1 are where the new features are merged into master
A2 would be where a new Version Packages pull request is created
B2 is where it would merge the changes if the pull request is still open

A2 is correctly triggering GH Actions, while B2 is not

Thanks

**Comment by Andarist** [comment]
Hah, that's a little bit strange - I would suspect that it's a problem with triggers that you have set up for your CI job. Could you paste in your `.yml` for that (I'm assuming that you are using GitHub Actions)? Is CI re-triggered if you do a similar scenario manually using any other branch?

**Comment by emilgp** [comment]
Yes using GH actions, master CI branch has:
```
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run lint
      - run: npm run build

      - id: changesets
        uses: changesets/action@master
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

npm run release does a `npm run build && npx changeset publish`

And on pull requests:
```
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm ci
      - run: npm run lint
      - run: npm run build
```

On feature/* branches, this PR action runs whenever pull requests are created or updated with new commits.

On changeset-release/master branches (the Version Packages pull request) will use my PAT and trigger the action:
![Screenshot 2021-02-10 at 11 00 51 PM 2](https://user-images.githubusercontent.com/869397/107528191-886d7880-6bf4-11eb-9e0e-13b4cef8847c.png)

But the next changes to master would be pushed by github-actions bot which won't trigger the action:
![Screenshot 2021-02-10 at 11 00 51 PM](https://user-images.githubusercontent.com/869397/107528252-958a6780-6bf4-11eb-969c-c633eb72a363.png)

**Comment by Andarist** [comment]
Wow, that's quite strange - the PRs are opened & updated using very similar logic:
https://github.com/changesets/action/blob/b3300fad33b6ab794313da28d27424c0e2f78991/src/run.ts#L266-L283
that uses the very same Octokit instance that is created using the same token:
https://github.com/changesets/action/blob/b3300fad33b6ab794313da28d27424c0e2f78991/src/run.ts#L172

But actually, all commits (including the first one that "creates" a PR) are signed by a github-actions bot:
https://github.com/changesets/action/blob/b3300fad33b6ab794313da28d27424c0e2f78991/src/index.ts#L24-L27
It's only the PR itself that is authored by your personal account.

One thing - could you change your CI triggers to:
```yml
on: [pull_request, push]
```

**Comment by emilgp** [comment]
i'd think it would still not get triggered with a push from github-actions bot. i should set up a public repo to repro this, didn't realize there's free minutes for gh actions

**Comment by ianwalter** [comment]
I'm facing this issue as well. Maybe this is a bug with GitHub Actions. Perhaps it would be better to rename `GITHUB_TOKEN` to something else? GitHub doesn't allow you create a secret called `GITHUB_TOKEN`. It says it's an "invalid name" so maybe there's a bug where the environment variable gets overwritten but only on subsequent updates to the PR.

**Comment by Andarist** [comment]
That's an interesting idea - would be great if you could test this with a different name for this env. [`patch-package`](https://github.com/ds300/patch-package) might come in handy for this.

**Comment by ianwalter** [comment]
I was wrong. I read another issue that reminded me that we need to tell the checkout action to use the PAT as well. This looks like your issue as well @emilgp. It should look like:

```yml
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
```

**Comment by emilgp** [comment]
my PAT token actually stopped working, i keep getting this error after 
`/usr/bin/git push origin HEAD:changeset-release/master --force`
```
UnhandledPromiseRejectionWarning: HttpError: Validation Failed: {"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}
```

Regenerating the token didn't help. Changed back to GITHUB_TOKEN which creates the Version Packages PR but does not trigger the PR action. Tried changing back to PAT then it worked again, so i can't tell if applying changes from @ianwalter would help. 

I'm facing issues around the tokens in other actions as well, will have to see how github support figures them out.

**Comment by Andarist** [comment]
@ianwalter did switching to PAT solve your problem entirely? are workflows run even after the versioning PR gets force-pushed after a fresh merge to your main branch?

@emilgp let me know if I can be of any assistance, while you are mailing

**Comment by JakeGinnivan** [comment]
Any action with GITHUB_TOKEN will not trigger actions. This is to stop circular triggers.

Basically if you want to do anything with GITHUB and have an action trigger you need to use your own PAT rather than GITHUB_TOKEN.

So if you manually merged the PR then the master workflow would run, but any pushes to the PR would not.

**Comment by ianwalter** [comment]
> @ianwalter did switching to PAT solve your problem entirely? are workflows run even after the versioning PR gets force-pushed after a fresh merge to your main branch?

Yes

**Comment by Andarist** [comment]
> Any action with GITHUB_TOKEN will not trigger actions. This is to stop circular triggers.

Right. I don't think this is really that developer-friendly though. There is no such guard when using other CI providers and somehow we don't end up having this problem that often 😉

**Comment by JakeGinnivan** [comment]
Yep, it is an annoying limitation. We have created a service account and generated a PAT which we put in our organisations secrets and use that for anything we need to trigger actions.

**Comment by jonrohan** [comment]
This could be addressed by allowing configuration of the git user here https://github.com/changesets/action/blob/aacbc223926b9a6ac55d5922b90fd2a09e1fcfa9/src/gitUtils.ts#L4-L17

**Comment by Andarist** [comment]
@jonrohan are you saying that using PAT is not enough and GitHub doesn't trigger workflows based on the user as well?

**Comment by jonrohan** [comment]
PAT tokens work on triggering actions, but this library is still using the GitHub action token when pushing commits

**Comment by Andarist** [comment]
@jonrohan not sure if I understand the issue you are facing. To the best of my knowledge, this is not possible - if you only give the PAT to us. We can't access the secrets on our own so the only way for us to access any token is for users to give it to us. Which is done using the `GITHUB_TOKEN` input. So it's entirely not to us what token we'll try to use - it's up to the user.

**Comment by madou** [comment]
Hi I seem to have ran into this - subsequent "force pushes" to the version PRs aren't having CI run - the branches are "force pushed" by github-actions-bot, not the user account.

Strangely - keystone js doesn't seem to have this problem? What's different?

Mine: https://github.com/atlassian-labs/compiled/pull/698

<img width="830" alt="image" src="https://user-images.githubusercontent.com/6801309/113506308-61de1500-9587-11eb-8a35-cda845d7003d.png">

Keystones: https://github.com/keystonejs/keystone/pull/5086

<img width="838" alt="image" src="https://user-images.githubusercontent.com/6801309/113506311-69052300-9587-11eb-8d20-d2a1b550fac6.png">

**Comment by mitchellhamilton** [comment]
It'll be because of this line: https://github.com/keystonejs/keystone/blob/955787055a54fb33eb45c80dd39fa86a9ff632a0/.github/workflows/release.yml#L17

**Comment by madou** [comment]
Interesting! Will change it and see what happens.

**Comment by denieler** [comment]
yep, indeed, guys, it works for us too 👍 maybe we should include this recommendation to the docs?

**Comment by theoephraim** [comment]
For anyone else landing here, the TLDR is

When using the default GITHUB_TOKEN to perform git operations in actions, it acts as the github bot, and the platform purposefully does not trigger subsequent actions for the purpose of avoiding accidental recursive action loops...

**To fix:**
- create a new personal access token (with permissions to mess with PRs), and pass into `changesets/action` in env as `GITHUB_TOKEN`
- add `persist-credentials: false` to the `actions/checkout`, or else it will continue using the default token when it does a force push to update your versioned release PR

```
name: Release packages

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # this is needed so that pushes to the version release branch will use the token we pass in below
          # otherwise the default token will be used, and actions on that versioned release branch will not be triggered
          persist-credentials: false
      # ... anything else you need to do ...
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: "[Changesets] Versioned release"
          commit: "[Changesets] Create versioned packages for publishing"
          publish: pnpm run changeset:publish
          version: pnpm run changeset:version
        env:
          # we use a personal token instead of the automatic repo one so that the binary release workflow will be triggered
          # (see https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow)
          GITHUB_TOKEN: ${{ secrets.PUBLISHING_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
