### ISSUE TITLE
Latest commit on master breaking non-pnp Yarn installs 

### ISSUE THREAD

**Issue by stramel** [changesets/action#72]
Commit https://github.com/changesets/action/commit/bf4c6120189e0b92f82c19a222764fbf9fbe2ce2

Is breaking on our Yarn v1 (non-pnp) installs.

I switched the action back to use the previous commit and everything works fine again. (https://github.com/changesets/action/commit/b3300fad33b6ab794313da28d27424c0e2f78991)

The error I was getting is as follows:

```
Error: Cannot find module '@changesets/cli/package.json'
Require stack:
Error: Cannot find module '@changesets/cli/package.json'
Require stack:
- /home/runner/work/_actions/changesets/action/master/dist/index.js
- /home/runner/work/_actions/changesets/action/master/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at f (/home/runner/work/_actions/changesets/action/master/dist/index.js:1:293)
    at f (/home/runner/work/_actions/changesets/action/master/dist/index.js:1:233)
    at p (/home/runner/work/_actions/changesets/action/master/dist/index.js:1:544)
    at Object.w [as runVersion] (/home/runner/work/_actions/changesets/action/master/dist/index.js:906:3310)
    at async /home/runner/work/_actions/changesets/action/master/dist/index.js:908:1597 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/changesets/action/master/dist/index.js'
  ]
}
```

**Comment by stramel** [comment]
Sorry, just saw that #71 is addressing this issue. Will keep this open until it is merged for other users to easily find the issue.

**Comment by jacobwgillespie** [comment]
#71 has merged, this issue may be able to be closed.

**Comment by stramel** [comment]
Verified the changes worked on our setup. Thanks for the quick fix @jacobwgillespie!

**Comment by ManasMaji** [comment]
Hi @stramel , @jacobwgillespie I am trying to setup a Github action using `changesets` to publish packages from a `yarn + lerna` managed mono-repo and I am facing a similar issue. I am not sure what I am doing wrong - 
```
Error: Cannot find module '@changesets/cli/package.json'
Require stack:
- /home/runner/work/aem-cloud-service-source-migration/aem-cloud-service-source-migration/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at p (/home/runner/work/_actions/changesets/action/master/dist/index.js:906:437)
    at o (/home/runner/work/_actions/changesets/action/master/dist/index.js:906:546)
    at Object.module.exports [as default] (/home/runner/work/_actions/changesets/action/master/dist/index.js:906:574)
    at Object.b [as runVersion] (/home/runner/work/_actions/changesets/action/master/dist/index.js:908:3356)
    at async /home/runner/work/_actions/changesets/action/master/dist/index.js:910:1597 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/aem-cloud-service-source-migration/aem-cloud-service-source-migration/noop.js'
  ]
}
Error: Cannot find module '@changesets/cli/package.json'
Require stack:
- /home/runner/work/aem-cloud-service-source-migration/aem-cloud-service-source-migration/noop.js
```
This is my publish action workflow : 
```
name: Publish Packages

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10
          
      - name: Install Dependencies
        run: yarn

      - name: Execute Tests
        run: yarn test

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@master
        with:
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
Any pointers would be immensely helpful.
