### ISSUE TITLE
Publishing of Yarn 2 workspaces won't remove version prefix

### ISSUE THREAD

**Issue by mheob** [changesets/action#95]
In [our monorepo](https://github.com/easyfeedback/RCL/blob/main/packages/buttons/package.json) we use the [native Yarn 2 workspace prefixes](https://yarnpkg.com/features/workspaces#publishing-workspaces). For example, it looks like this:

```json
{
  "dependencies": {
    "@easyfeedback/theme": "workspace:^1.1.1"
  },
}
```

If we now use `yarn pack` or `yarn npm publish`, the prefix is removed, as explained in the link above.
Unfortunately, this does not work when using the `changesets/action`.

My wokflow looks like this:

```yaml
# ...

- name: Create Release Pull Request or Publish to GitHub packages
  uses: changesets/action@master
  with:
    commit: "Update version and deploy packages"
    title: "Update version and deploy packages"
    publish: yarn changeset publish
    version: yarn changeset version
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

# ...
```
